[build]
builder = "nixpacks"
watchPatterns = ["**/*.py"]

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --timeout-keep-alive 600 --workers 1"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on-failure"
